<Project>

  <PropertyGroup>
    <IsShadowProject Condition="$(MSBuildProjectName.EndsWith('.shadow'))">true</IsShadowProject>
    <IsSubActionProject Condition="'$(IsShadowProject)'=='true' and
      $(MSBuildProjectDirectory.Contains('\SubActions\'))">true</IsSubActionProject>
    <SubActionSourceFile>$(MSBuildProjectName.Replace('.shadow',''))</SubActionSourceFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsShadowProject)'=='true'">
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <NoWarn>CS8321</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsShadowProject)'=='true'">
    <Compile Include="$(MSBuildThisFileDirectory)_shims\CPHStub.cs"/>
  </ItemGroup>

  <ItemGroup Condition="'$(IsShadowProject)'=='true'">
    <Reference Include="Streamer.bot.Plugin.Interface">
      <HintPath>C:\Users\ville\myfiles\streaming-programs\streamerbot-portable-production\Streamer.bot\Streamer.bot.Plugin.Interface.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(IsSubActionProject)'=='true'">
    <Compile Include="$(MSBuildProjectDirectory)\$(SubActionSourceFile).cs"/>
  </ItemGroup>

  <ItemGroup Condition="'$(IsSubActionProject)'=='true' and '$(UseBroStreamerTools)'=='true'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)dlls\BroStreamerTools\BroStreamerTools.csproj"/>
  </ItemGroup>

  <ItemGroup Condition="'$(IsSubActionProject)'=='true' and '$(UseNewtonsoftJson)'=='true'">
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
  </ItemGroup>

</Project>
