<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="SkipCurrentAlert.cs"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\..\..\dlls\BroStreamerTools\BroStreamerTools.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
  </ItemGroup>
</Project>
